---
# Cloudformation template for ec2 instances on app tier in an ASG group
AWSTemplateFormatVersion: "2010-09-09"
Description: This template deploys notejam's app/db/presentation tier

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: notejam

  SSHKey:
    Description: SSH keypair used when launching ec2 instances
    Type: String
    Default: notejam

  InstanceType:
    Description: Type of EC2 instance launched
    Type: String
    Default: t2.micro

  AmiType:
    Description: AMI image type on ca-central-1, default to Amazon Linux
    Type: String
    Default: ami-054362537f5132ce2

Resources:
  BastionLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      SecurityGroups:
        - { "Fn::ImportValue": !Sub "${EnvironmentName}-BastionSG" }
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiType
      KeyName: !Ref SSHKey
      AssociatePublicIpAddress: true

  BastionASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref BastionLaunchConfiguration
      MinSize: 2
      MaxSize: 4
      VPCZoneIdentifier:
        - { "Fn::ImportValue": !Sub "${EnvironmentName}-PublicSubnet1" }
        - { "Fn::ImportValue": !Sub "${EnvironmentName}-PublicSubnet2" }
        
